### ISSUE TITLE
redmine_extensions and remine 3.4

### ISSUE THREAD

**Issue by kal60** [easyredmine/redmine_extensions#3]
Hi!

I tried to install the redmine plugin generator.
I downloaded the plugin but I can't get it running with redmine 3.4.

The plugin requires the gem redmine_extensions which is available as Version 0.2.3 from Aug 30th.
When calling the plugin I'll get an error with the call of the function column_header().

in .../redmine_extensions-mod/app/views/easy_queries/_entities.html.erb the function column_header(column) is called with one argument, but redmine 3.4 requires two: column_header(query,column), so the extension are running into an error.

I also tried to use the redmine_extension plugin but get the same error.

I can't find a newer version of redmine_extension with this error fixe. Can you help me ?

Zhanks in advance

Knut

**Comment by luk4s** [comment]
Hello,
redmine3.x is not support / compatible. Please upgrade your Redmine.
